package compiler

enum Instruction:
  case MOVE(a: Int, b: Int)
  case LOADK(a: Int, bx: Int)
  case GETUPVAL(a: Int, b: Int)
  case GETTABLE(a: Int, b: Int, c: Int)
  case SETUPVAL(a: Int, b: Int)
  case SETTABLE(a: Int, b: Int, c: Int)
  case NEWTABLE(a: Int, b: Int, c: Int)
  case ADD(a: Int, b: Int, c: Int)
  case SUB(a: Int, b: Int, c: Int)
  case MUL(a: Int, b: Int, c: Int)
  case DIV(a: Int, b: Int, c: Int)
  case MOD(a: Int, b: Int, c: Int)
  case POW(a: Int, b: Int, c: Int)
  case UNM(a: Int, b: Int)
  case NOT(a: Int, b: Int)
  case LEN(a: Int, b: Int)
  case CONCAT(a: Int, b: Int, c: Int)
  case JMP(sBx: Int)
  case EQ(a: Int, b: Int, c: Int)
  case LT(a: Int, b: Int, c: Int)
  case LE(a: Int, b: Int, c: Int)
  case TEST(a: Int, c: Int)
  case FORLOOP(a: Int, sBx: Int)
  case FORPREP(a: Int, sBx: Int)
  case RETURN(a: Int)
  case CALL(a: Int, b: Int)
  case CLOSURE(a: Int, bx: Int)
